# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  IMAGE_NAME: Cypress_Github_Actions
  TAGS: v1 ${{ github.sha }}

jobs:
  Install-dependencies:
   runs-on: ubuntu-latest
   steps:
      - name: Install CLI tools from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          # "mirror" is the default source, so this is optional.
          source: "mirror"
          # Installs the latest kam release.
          kam: "latest"
          # Installs the latest release of oc with the major version 3.
          # This is equivalent to "3.x" or "^3".
          oc: "3"
          # Installs the latest release of odo with the major version 2, and the minor version 0.
          # This would install odo 2.0.3, but not odo 2.1.0.
          odo: "2.0"
          # Installs the latest release of helm.
          helm: "latest"
          # Installs the latest release of kustomize.
          kustomize: "latest"
      - name: Run installed tools
        shell: bash
        run: |
          set -x
          helm version
          kam version
          kustomize version
          oc version
          odo version || true

  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/   
    steps:
      - name: Checkout Git Code
        uses: actions/checkout@v3
      
      # Setup S2i and Build container image
      - name: Setup and Build
        id: build_image
        uses: redhat-actions/s2i-build@v2
        with:
          path_context: '.'
          # Builder image for a java project
          builder_image: 'centos/nodejs-10-centos7'
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}

      # Push Image to Quay registry
      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: quay.io/${{ secrets.QUAY_USERNAME }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          
  Cypress-Test:
   runs-on: ubuntu-latest
   strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v3
 
     - name: Run Cypress Test
       uses: cypress-io/github-action@v4
       with:
         command: npx cypress run
         browser: chrome
